/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.cep.modelo.EnderecoDTO;
import br.com.cep.webservice.CepRest;
import br.com.senac.contolador.Controlador;
import br.com.senac.dao.ClienteDao;
import br.com.senac.dao.ClienteDaoImpl;
import br.com.senac.dao.HibernateUtil;
import br.com.senac.entidade.Cliente;
import br.com.senac.entidade.Endereco;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author Vítor
 */
public class CadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCliente
     */
    private Session session;
    private Cliente cliente;
    private ClienteDao clienteDao;
    private Endereco endereco;
    private Controlador controlador;

    public CadastroCliente() {
        initComponents();
        clienteDao = new ClienteDaoImpl();
        lbAstEmail.setVisible(false);
        lbAstName.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        lbEmail = new javax.swing.JLabel();
        lbTel = new javax.swing.JLabel();
        varEmail = new javax.swing.JTextField();
        lbCep = new javax.swing.JLabel();
        varCep = new javax.swing.JTextField();
        lbNúmero = new javax.swing.JLabel();
        varNumero = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        lbLogradouro = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        lbUf = new javax.swing.JLabel();
        varLocalidade = new javax.swing.JTextField();
        lbLocalidade = new javax.swing.JLabel();
        varUf = new javax.swing.JTextField();
        varLogradouro = new javax.swing.JTextField();
        varBairro = new javax.swing.JTextField();
        lbComplemento = new javax.swing.JLabel();
        varComplemento = new javax.swing.JTextField();
        varTel = new javax.swing.JFormattedTextField();
        lbAstName = new javax.swing.JLabel();
        lbAstEmail = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Cadastro Cliente");

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNome.setText("Nome:");
        lbNome.setAutoscrolls(true);
        lbNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btSalvar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setAutoscrolls(true);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmail.setText("E-mail:");
        lbEmail.setAutoscrolls(true);
        lbEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbTel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTel.setText("Telefone:");
        lbTel.setAutoscrolls(true);
        lbTel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        varEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varEmailFocusLost(evt);
            }
        });

        lbCep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCep.setText("CEP:");
        lbCep.setAutoscrolls(true);
        lbCep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varCep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        varCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varCepFocusLost(evt);
            }
        });

        lbNúmero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNúmero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNúmero.setText("Número:");
        lbNúmero.setAutoscrolls(true);
        lbNúmero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        varNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setAutoscrolls(true);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbLogradouro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLogradouro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLogradouro.setText("Logradouro:");
        lbLogradouro.setAutoscrolls(true);
        lbLogradouro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbBairro.setText("Bairro:");
        lbBairro.setAutoscrolls(true);
        lbBairro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbUf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUf.setText("UF:");
        lbUf.setAutoscrolls(true);
        lbUf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbLocalidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLocalidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLocalidade.setText("Localidade:");
        lbLocalidade.setAutoscrolls(true);
        lbLocalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbComplemento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbComplemento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbComplemento.setText("Complemento:");
        lbComplemento.setAutoscrolls(true);
        lbComplemento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        try {
            varTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbAstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstName.setForeground(new java.awt.Color(255, 0, 0));
        lbAstName.setText("*");

        lbAstEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstEmail.setForeground(new java.awt.Color(255, 0, 0));
        lbAstEmail.setText("*");

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbLocalidade)
                        .addComponent(lbNúmero)
                        .addComponent(lbCep)
                        .addComponent(lbLogradouro)
                        .addComponent(lbBairro)
                        .addComponent(lbComplemento))
                    .addComponent(lbNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbAstName))
                            .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(varComplemento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(varLocalidade, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbUf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(varTel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(varCep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(varEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1))))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(varEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTel)
                    .addComponent(varTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(varCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCep))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNúmero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogradouro)
                    .addComponent(varLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBairro)
                    .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUf)
                    .addComponent(varLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocalidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplemento)
                    .addComponent(varComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String nome = varNome.getText().trim();
        String email = varEmail.getText().trim();
        String telefone = varTel.getText();
        
        
        if (nome.isEmpty()) {
            lbAstName.setVisible(true);
            if (!email.isEmpty()) {
                lbAstEmail.setVisible(false);
            }
        }
        if (email.isEmpty()) {
            lbAstEmail.setVisible(true);
            if (!nome.isEmpty()) {
                lbAstName.setVisible(false);
            }
        }

        controlador.valida_Cliente(varNome.getText().trim(), varEmail.getText().trim(), varTel.getText().trim());
        if (true) {

        } else {
            cliente = new Cliente(false, varNome.getText().trim(), varEmail.getText().trim(), varNumero.getText().trim());
            List<Endereco> enderecos = new ArrayList<>();
//            endereco = new Endereco(enderecoApi.getLogradouro(), varNumero.getText().trim(), enderecoApi.getBairro(), enderecoApi.getLocalidade(), 
//                    enderecoApi.getComplemento(), enderecoApi.getUf());

            enderecos.add(endereco);
            cliente.setEnderecos(enderecos);
            for (Endereco endereco : enderecos) {
                endereco.setPessoa(cliente);
            }
            session = HibernateUtil.abrirConexao();
            clienteDao.saveOrAlter(cliente, session);
            session.close();
            System.out.println("ID: " + cliente.getId());

            JOptionPane.showMessageDialog(null, "Ta salvo meu filho");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Boolean a = controlador.valida_email(varEmail.getText().trim());
        System.out.println(a);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void varEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varEmailFocusLost
        Boolean a = controlador.valida_email(varEmail.getText().trim());
        System.out.println(a);
    }//GEN-LAST:event_varEmailFocusLost

    private void varCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varCepFocusLost
        CepRest cepRest = new CepRest();
        EnderecoDTO enderecoApi = cepRest.pesquisarCep(varCep.getText());
        if (enderecoApi == null) {
            JOptionPane.showMessageDialog(null, "O Cep informado não existe");
        } else {
            btSalvar.setEnabled(true);
        }
    }//GEN-LAST:event_varCepFocusLost

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbAstEmail;
    private javax.swing.JLabel lbAstName;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbLocalidade;
    private javax.swing.JLabel lbLogradouro;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNúmero;
    private javax.swing.JLabel lbTel;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUf;
    private javax.swing.JTextField varBairro;
    private javax.swing.JTextField varCep;
    private javax.swing.JTextField varComplemento;
    private javax.swing.JTextField varEmail;
    private javax.swing.JTextField varLocalidade;
    private javax.swing.JTextField varLogradouro;
    private javax.swing.JTextField varNome;
    private javax.swing.JFormattedTextField varNumero;
    private javax.swing.JFormattedTextField varTel;
    private javax.swing.JTextField varUf;
    // End of variables declaration//GEN-END:variables
}
