/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.cep.modelo.EnderecoDTO;
import br.com.cep.webservice.CepRest;
import br.com.senac.contolador.Controlador;
import br.com.senac.dao.ClienteDao;
import br.com.senac.dao.ClienteDaoImpl;
import br.com.senac.dao.HibernateUtil;
import br.com.senac.entidade.Cliente;
import br.com.senac.entidade.Endereco;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author Vítor
 */
public class CadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCliente
     */
    private Session session;
    private Cliente cliente;
    private ClienteDao clienteDao;
    private Endereco endereco;
    private Controlador controlador;
    private EnderecoDTO enderecoDTO;

    public CadastroCliente() {
        initComponents();
        clienteDao = new ClienteDaoImpl();
        enderecoDTO = new EnderecoDTO();
        lbAstEmail.setVisible(false);
        lbAstName.setVisible(false);
        lbAstUf.setVisible(false);
        lbAstLocal.setVisible(false);
        lbAstBairro.setVisible(false);
        lbAstNum.setVisible(false);
        lbAstLograd.setVisible(false);
        cliente = new Cliente();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        lbEmail = new javax.swing.JLabel();
        lbTel = new javax.swing.JLabel();
        varEmail = new javax.swing.JTextField();
        lbCep = new javax.swing.JLabel();
        varCep = new javax.swing.JTextField();
        lbNúmero = new javax.swing.JLabel();
        varNumero = new javax.swing.JFormattedTextField();
        lbLogradouro = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        lbUf = new javax.swing.JLabel();
        varLocalidade = new javax.swing.JTextField();
        lbLocalidade = new javax.swing.JLabel();
        varUf = new javax.swing.JTextField();
        varLogradouro = new javax.swing.JTextField();
        varBairro = new javax.swing.JTextField();
        lbComplemento = new javax.swing.JLabel();
        varComplemento = new javax.swing.JTextField();
        varTel = new javax.swing.JFormattedTextField();
        lbAstName = new javax.swing.JLabel();
        lbAstEmail = new javax.swing.JLabel();
        lbAstNum = new javax.swing.JLabel();
        lbAstLograd = new javax.swing.JLabel();
        lbAstBairro = new javax.swing.JLabel();
        lbAstUf = new javax.swing.JLabel();
        lbAstLocal = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadrastro Cliente");
        setToolTipText("");

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Cadastro Cliente");

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNome.setText("Nome:");
        lbNome.setAutoscrolls(true);
        lbNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btSalvar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setAutoscrolls(true);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmail.setText("E-mail:");
        lbEmail.setAutoscrolls(true);
        lbEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbTel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTel.setText("Telefone:");
        lbTel.setAutoscrolls(true);
        lbTel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        varEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varEmailFocusLost(evt);
            }
        });

        lbCep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCep.setText("CEP:");
        lbCep.setAutoscrolls(true);
        lbCep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varCep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        varCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varCepFocusLost(evt);
            }
        });

        lbNúmero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNúmero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNúmero.setText("Número:");
        lbNúmero.setAutoscrolls(true);
        lbNúmero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        varNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        varNumero.setEnabled(false);

        lbLogradouro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLogradouro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLogradouro.setText("Logradouro:");
        lbLogradouro.setAutoscrolls(true);
        lbLogradouro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbBairro.setText("Bairro:");
        lbBairro.setAutoscrolls(true);
        lbBairro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbUf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUf.setText("UF:");
        lbUf.setAutoscrolls(true);
        lbUf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varLocalidade.setEnabled(false);

        lbLocalidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLocalidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLocalidade.setText("Localidade:");
        lbLocalidade.setAutoscrolls(true);
        lbLocalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varUf.setEnabled(false);

        varLogradouro.setEnabled(false);

        varBairro.setEnabled(false);

        lbComplemento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbComplemento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbComplemento.setText("Complemento:");
        lbComplemento.setAutoscrolls(true);
        lbComplemento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varComplemento.setEnabled(false);

        try {
            varTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        varTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varTelFocusLost(evt);
            }
        });

        lbAstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstName.setForeground(new java.awt.Color(255, 0, 0));
        lbAstName.setText("*");

        lbAstEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstEmail.setForeground(new java.awt.Color(255, 0, 0));
        lbAstEmail.setText("*");

        lbAstNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstNum.setForeground(new java.awt.Color(255, 0, 0));
        lbAstNum.setText("*");

        lbAstLograd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstLograd.setForeground(new java.awt.Color(255, 0, 0));
        lbAstLograd.setText("*");

        lbAstBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstBairro.setForeground(new java.awt.Color(255, 0, 0));
        lbAstBairro.setText("*");

        lbAstUf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstUf.setForeground(new java.awt.Color(255, 0, 0));
        lbAstUf.setText("*");

        lbAstLocal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstLocal.setForeground(new java.awt.Color(255, 0, 0));
        lbAstLocal.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbLocalidade)
                        .addComponent(lbNúmero)
                        .addComponent(lbCep)
                        .addComponent(lbLogradouro)
                        .addComponent(lbBairro)
                        .addComponent(lbComplemento))
                    .addComponent(lbNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstNum))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(varTel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(varCep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(varEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(varLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstLograd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(varComplemento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(varLocalidade, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbAstLocal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbAstBairro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbUf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varUf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstUf)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(varEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTel)
                    .addComponent(varTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNúmero)
                    .addComponent(lbAstNum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogradouro)
                    .addComponent(varLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstLograd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBairro)
                    .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUf)
                    .addComponent(varLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocalidade)
                    .addComponent(lbAstUf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplemento)
                    .addComponent(varComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String nome = varNome.getText().trim();
        String email = varEmail.getText().trim();
        String telefone = varTel.getText();

        if (!nome.isEmpty() && !email.isEmpty() && telefone.length() >= 12) {
            if (controlador.validaCliente(cliente, nome, email, telefone)) {
                String logradouro = varLogradouro.getText().trim();
                String numero = varNumero.getText().trim();
                String bairro = varBairro.getText().trim();
                String localidade = varLocalidade.getText().trim();
                String uf = varUf.getText().trim();

                if (controlador.validaEnd(cliente, endereco, logradouro, numero, bairro, localidade, uf, varComplemento.getText().trim(), varCep.getText().trim())) {
                    try {
                        session = HibernateUtil.abrirConexao();
                        clienteDao.saveOrAlter(cliente, session);
                        JOptionPane.showMessageDialog(null, "Ta salvo meu filho");
                    } catch (Exception e) {
                        System.out.println("Erro ao salvar Cliente " + e);
                    } finally {
                        session.close();
                    }

                    JOptionPane.showMessageDialog(null, "Dados salvos!");

                    
                } else {
                    // Mostra Asterisco de campos obrigatórios e retira o que estiver preenchido restante abaixo de CEP
                    if (logradouro.isEmpty()) {
                        lbAstLograd.setVisible(true);
                        if (!numero.isEmpty()) {
                            lbAstNum.setVisible(false);
                        }
                        if (!bairro.isEmpty()) {
                            lbAstBairro.setVisible(false);
                        }
                        if (!localidade.isEmpty()) {
                            lbAstLocal.setVisible(false);
                        }
                        if (!uf.isEmpty()) {
                            lbAstUf.setVisible(false);
                        }
                    }
                    if (numero.isEmpty()) {
                        lbAstNum.setVisible(true);
                        if (!logradouro.isEmpty()) {
                            lbAstLograd.setVisible(false);
                        }
                        if (!bairro.isEmpty()) {
                            lbAstBairro.setVisible(false);
                        }
                        if (!localidade.isEmpty()) {
                            lbAstLocal.setVisible(false);
                        }
                        if (!uf.isEmpty()) {
                            lbAstUf.setVisible(false);
                        }
                    }
                    if (bairro.isEmpty()) {
                        lbAstBairro.setVisible(true);
                        if (!localidade.isEmpty()) {
                            lbAstLocal.setVisible(false);
                        }
                        if (!uf.isEmpty()) {
                            lbAstUf.setVisible(false);
                        }
                        if (!numero.isEmpty()) {
                            lbAstNum.setVisible(false);
                        }
                        if (!logradouro.isEmpty()) {
                            lbAstLograd.setVisible(false);
                        }
                    }
                    if (localidade.isEmpty()) {
                        lbAstLocal.setVisible(true);
                        if (!uf.isEmpty()) {
                            lbAstUf.setVisible(false);
                        }
                        if (!numero.isEmpty()) {
                            lbAstNum.setVisible(false);
                        }
                        if (!logradouro.isEmpty()) {
                            lbAstLograd.setVisible(false);
                        }
                        if (!bairro.isEmpty()) {
                            lbAstBairro.setVisible(false);
                        }

                    }
                    if (uf.isEmpty()) {
                        lbAstUf.setVisible(true);
                        if (!numero.isEmpty()) {
                            lbAstNum.setVisible(false);
                        }
                        if (!logradouro.isEmpty()) {
                            lbAstLograd.setVisible(false);
                        }
                        if (!bairro.isEmpty()) {
                            lbAstBairro.setVisible(false);
                        }
                        if (!localidade.isEmpty()) {
                            lbAstLocal.setVisible(false);
                        }
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, "Informe um nome maior que 3 Caracteres");
            }
        } else {
            if (nome.isEmpty()) {
                lbAstName.setVisible(true);
                if (!email.isEmpty()) {
                    lbAstEmail.setVisible(false);
                }
            }
            if (email.isEmpty()) {
                lbAstEmail.setVisible(true);
                if (!nome.isEmpty()) {
                    lbAstName.setVisible(false);
                }
            }
        }


    }//GEN-LAST:event_btSalvarActionPerformed

    private void varEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varEmailFocusLost
        String email = varEmail.getText().trim();

        if (email.contains("@") && email.contains(".")) {
            String emailBd = "";
            try {
                session = HibernateUtil.abrirConexao();
                System.out.println(email);
                emailBd = clienteDao.askPerEmail(email, session);

            } catch (Exception e) {
                System.out.println("Erro ao verificar e-mail " + e);

            } finally {
                session.close();
            }
            System.out.println(emailBd);
            if (emailBd == null) {
                cliente.setEmail(email);
            } else {

                JOptionPane.showMessageDialog(null, "Email já cadastrado!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Digite um e-mail!");
        }
    }//GEN-LAST:event_varEmailFocusLost

    private void varCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varCepFocusLost
        CepRest cepRest = new CepRest();
        EnderecoDTO enderecoApi = cepRest.pesquisarCep(varCep.getText());
        if (enderecoApi == null) {
            JOptionPane.showMessageDialog(null, "O Cep informado não existe");
        } else {
            varNumero.setEnabled(true);
            varLogradouro.setEnabled(true);
            varBairro.setEnabled(true);
            varLocalidade.setEnabled(true);
            varUf.setEnabled(true);
            varComplemento.setEnabled(true);

            varLogradouro.setText(enderecoApi.getLogradouro());
            varBairro.setText(enderecoApi.getBairro());
            varLocalidade.setText(enderecoApi.getLocalidade());
            varUf.setText(enderecoApi.getUf());
            varComplemento.setText(enderecoApi.getComplemento());
            btSalvar.setEnabled(true);

        }
    }//GEN-LAST:event_varCepFocusLost

    private void varTelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varTelFocusLost
        String tel = varTel.getText();
        if (!tel.isEmpty()) {
            cliente.setTelefone(tel);
        } else {
            JOptionPane.showMessageDialog(null, "Informe um Número de Telefone!");
        }
    }//GEN-LAST:event_varTelFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel lbAstBairro;
    private javax.swing.JLabel lbAstEmail;
    private javax.swing.JLabel lbAstLocal;
    private javax.swing.JLabel lbAstLograd;
    private javax.swing.JLabel lbAstName;
    private javax.swing.JLabel lbAstNum;
    private javax.swing.JLabel lbAstUf;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbLocalidade;
    private javax.swing.JLabel lbLogradouro;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNúmero;
    private javax.swing.JLabel lbTel;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUf;
    private javax.swing.JTextField varBairro;
    private javax.swing.JTextField varCep;
    private javax.swing.JTextField varComplemento;
    private javax.swing.JTextField varEmail;
    private javax.swing.JTextField varLocalidade;
    private javax.swing.JTextField varLogradouro;
    private javax.swing.JTextField varNome;
    private javax.swing.JFormattedTextField varNumero;
    private javax.swing.JFormattedTextField varTel;
    private javax.swing.JTextField varUf;
    // End of variables declaration//GEN-END:variables
}
