/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.cep.modelo.EnderecoDTO;
import br.com.cep.webservice.CepRest;
import br.com.senac.contolador.Controlador;
import br.com.senac.dao.ClienteDao;
import br.com.senac.dao.ClienteDaoImpl;
import br.com.senac.dao.HibernateUtil;
import br.com.senac.entidade.Cliente;
import br.com.senac.entidade.Endereco;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author Vítor
 */
public class ConsultaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaCliente
     */
    private Session session;
    private Cliente cliente;
    private ClienteDao clienteDao;
    private Endereco endereco;
    private Controlador controlador;
    private EnderecoDTO enderecoDTO;
    private DefaultTableModel tabelaModelo;
    private List<Cliente> clientes;
    
    
    public ConsultaCliente() {
        initComponents();
        clienteDao = new ClienteDaoImpl();
        enderecoDTO = new EnderecoDTO();
        lbAstEmail.setVisible(false);
        lbAstName.setVisible(false);
        lbAstUf.setVisible(false);
        lbAstLocal.setVisible(false);
        lbAstBairro.setVisible(false);
        lbAstNum.setVisible(false);
        lbAstLograd.setVisible(false);
        cliente = new Cliente();
        tabAlt.setVisible(false);
        tab.setEnabledAt(1, false);
        tabelaModelo = (DefaultTableModel) tabelaCliente.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAskNome = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        varAskNome = new javax.swing.JTextField();
        varAskTelefone = new javax.swing.JFormattedTextField();
        btBuscar = new javax.swing.JButton();
        lbEmail = new javax.swing.JLabel();
        varAskEmail = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        tabList = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        tabAlt = new javax.swing.JPanel();
        lbBairro = new javax.swing.JLabel();
        lbUf = new javax.swing.JLabel();
        varLocalidade = new javax.swing.JTextField();
        lbLocalidade = new javax.swing.JLabel();
        varUf = new javax.swing.JTextField();
        varLogradouro = new javax.swing.JTextField();
        varBairro = new javax.swing.JTextField();
        lbComplemento = new javax.swing.JLabel();
        varComplemento = new javax.swing.JTextField();
        varTel = new javax.swing.JFormattedTextField();
        lbAstName = new javax.swing.JLabel();
        lbNome1 = new javax.swing.JLabel();
        lbAstEmail = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        lbAstNum = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        lbAstLograd = new javax.swing.JLabel();
        lbEmail1 = new javax.swing.JLabel();
        lbAstBairro = new javax.swing.JLabel();
        lbTel = new javax.swing.JLabel();
        lbAstUf = new javax.swing.JLabel();
        varEmail = new javax.swing.JTextField();
        lbCep = new javax.swing.JLabel();
        lbAstLocal = new javax.swing.JLabel();
        varCep = new javax.swing.JTextField();
        lbNúmero = new javax.swing.JLabel();
        varNumero = new javax.swing.JFormattedTextField();
        lbLogradouro = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        varId = new javax.swing.JTextField();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setTitle("Consulta Cliente");

        lbAskNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAskNome.setForeground(new java.awt.Color(0, 0, 0));
        lbAskNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAskNome.setText("Nome:");
        lbAskNome.setAutoscrolls(true);
        lbAskNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTelefone.setForeground(new java.awt.Color(0, 0, 0));
        lbTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTelefone.setText("Telefone:");
        lbTelefone.setAutoscrolls(true);
        lbTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varAskNome.setBackground(new java.awt.Color(255, 255, 255));
        varAskNome.setForeground(new java.awt.Color(0, 0, 0));

        varAskTelefone.setBackground(new java.awt.Color(255, 255, 255));
        varAskTelefone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            varAskTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vítor\\Downloads\\pesquisa-de-lupa.png")); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(0, 0, 0));
        lbEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmail.setText("Email:");
        lbEmail.setAutoscrolls(true);
        lbEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varAskEmail.setBackground(new java.awt.Color(255, 255, 255));
        varAskEmail.setForeground(new java.awt.Color(0, 0, 0));

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btLimpar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vítor\\Downloads\\limpar-limpo.png")); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        tab.setForeground(new java.awt.Color(255, 255, 255));
        tab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab.setOpaque(true);
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });

        tabelaCliente.setForeground(new java.awt.Color(0, 0, 0));
        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "E-Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCliente.setColumnSelectionAllowed(true);
        tabelaCliente.getTableHeader().setReorderingAllowed(false);
        tabList.setViewportView(tabelaCliente);
        tabelaCliente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaCliente.getColumnModel().getColumnCount() > 0) {
            tabelaCliente.getColumnModel().getColumn(0).setMinWidth(50);
            tabelaCliente.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabelaCliente.getColumnModel().getColumn(0).setMaxWidth(70);
            tabelaCliente.getColumnModel().getColumn(1).setMinWidth(100);
            tabelaCliente.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        tab.addTab("Lista", tabList);

        tabAlt.setForeground(new java.awt.Color(255, 255, 255));

        lbBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbBairro.setForeground(new java.awt.Color(0, 0, 0));
        lbBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbBairro.setText("Bairro:");
        lbBairro.setAutoscrolls(true);
        lbBairro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbUf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUf.setForeground(new java.awt.Color(0, 0, 0));
        lbUf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUf.setText("UF:");
        lbUf.setAutoscrolls(true);
        lbUf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbLocalidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLocalidade.setForeground(new java.awt.Color(0, 0, 0));
        lbLocalidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLocalidade.setText("Localidade:");
        lbLocalidade.setAutoscrolls(true);
        lbLocalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbComplemento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbComplemento.setForeground(new java.awt.Color(0, 0, 0));
        lbComplemento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbComplemento.setText("Complemento:");
        lbComplemento.setAutoscrolls(true);
        lbComplemento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        try {
            varTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        varTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varTelFocusLost(evt);
            }
        });

        lbAstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstName.setForeground(new java.awt.Color(204, 0, 0));
        lbAstName.setText("*");

        lbNome1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNome1.setForeground(new java.awt.Color(0, 0, 0));
        lbNome1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNome1.setText("Nome:");
        lbNome1.setAutoscrolls(true);
        lbNome1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbAstEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstEmail.setForeground(new java.awt.Color(204, 0, 0));
        lbAstEmail.setText("*");

        varNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbAstNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstNum.setForeground(new java.awt.Color(204, 0, 0));
        lbAstNum.setText("*");

        btSalvar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.setAutoscrolls(true);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        lbAstLograd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstLograd.setForeground(new java.awt.Color(204, 0, 0));
        lbAstLograd.setText("*");

        lbEmail1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEmail1.setForeground(new java.awt.Color(0, 0, 0));
        lbEmail1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmail1.setText("E-mail:");
        lbEmail1.setAutoscrolls(true);
        lbEmail1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbAstBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstBairro.setForeground(new java.awt.Color(204, 0, 0));
        lbAstBairro.setText("*");

        lbTel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTel.setForeground(new java.awt.Color(0, 0, 0));
        lbTel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTel.setText("Telefone:");
        lbTel.setAutoscrolls(true);
        lbTel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbAstUf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstUf.setForeground(new java.awt.Color(204, 0, 0));
        lbAstUf.setText("*");

        varEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        varEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varEmailFocusLost(evt);
            }
        });

        lbCep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCep.setForeground(new java.awt.Color(0, 0, 0));
        lbCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCep.setText("CEP:");
        lbCep.setAutoscrolls(true);
        lbCep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbAstLocal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAstLocal.setForeground(new java.awt.Color(204, 0, 0));
        lbAstLocal.setText("*");

        varCep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        varCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varCepFocusLost(evt);
            }
        });

        lbNúmero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNúmero.setForeground(new java.awt.Color(0, 0, 0));
        lbNúmero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNúmero.setText("Número:");
        lbNúmero.setAutoscrolls(true);
        lbNúmero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        varNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbLogradouro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLogradouro.setForeground(new java.awt.Color(0, 0, 0));
        lbLogradouro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLogradouro.setText("Logradouro:");
        lbLogradouro.setAutoscrolls(true);
        lbLogradouro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbId.setForeground(new java.awt.Color(0, 0, 0));
        lbId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbId.setText("ID:");
        lbId.setAutoscrolls(true);
        lbId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varId.setEditable(false);
        varId.setEnabled(false);

        javax.swing.GroupLayout tabAltLayout = new javax.swing.GroupLayout(tabAlt);
        tabAlt.setLayout(tabAltLayout);
        tabAltLayout.setHorizontalGroup(
            tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAltLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbLocalidade)
                            .addComponent(lbNúmero)
                            .addComponent(lbCep)
                            .addComponent(lbLogradouro)
                            .addComponent(lbBairro)
                            .addComponent(lbComplemento))
                        .addComponent(lbEmail1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lbNome1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAltLayout.createSequentialGroup()
                        .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstName))
                    .addGroup(tabAltLayout.createSequentialGroup()
                        .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstNum))
                    .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(varTel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(varCep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabAltLayout.createSequentialGroup()
                        .addComponent(varEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstEmail))
                    .addGroup(tabAltLayout.createSequentialGroup()
                        .addComponent(varLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstLograd))
                    .addGroup(tabAltLayout.createSequentialGroup()
                        .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(tabAltLayout.createSequentialGroup()
                                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(varComplemento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(varLocalidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbAstLocal))
                            .addGroup(tabAltLayout.createSequentialGroup()
                                .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbAstBairro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbUf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varUf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAstUf))
                    .addComponent(varId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
            .addGroup(tabAltLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabAltLayout.setVerticalGroup(
            tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAltLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome1)
                    .addComponent(lbAstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail1)
                    .addComponent(varEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTel)
                    .addComponent(varTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNúmero)
                    .addComponent(lbAstNum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogradouro)
                    .addComponent(varLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstLograd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBairro)
                    .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUf)
                    .addComponent(varLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocalidade)
                    .addComponent(lbAstUf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAstLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplemento)
                    .addComponent(varComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        tab.addTab("Alterar", tabAlt);

        btAlterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vítor\\Downloads\\Alterar.png")); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vítor\\Downloads\\Excluir Usuario.png")); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEmail)
                    .addComponent(lbTelefone)
                    .addComponent(lbAskNome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(varAskEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addComponent(varAskNome)
                    .addComponent(varAskTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAskNome)
                            .addComponent(varAskNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(varAskTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTelefone))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmail)
                            .addComponent(varAskEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        varAskNome.setText("");
        varAskEmail.setText("");
        varAskTelefone.setText("");
        // Limpando a tabelaModelo
        tabelaModelo.setNumRows(0);
    }//GEN-LAST:event_btLimparActionPerformed

    private void varTelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varTelFocusLost
        String tel = varTel.getText();
        if (!tel.isEmpty()) {
            cliente.setTelefone(tel);
        } else {
            JOptionPane.showMessageDialog(null, "Informe um Número de Telefone!");
        }
    }//GEN-LAST:event_varTelFocusLost

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // Limpando lista
        clientes.clear();
        // Limpando a tabelaModelo
        tabelaModelo.setNumRows(0);
        Long id = Long.parseLong(varId.getText());
        
        String nome = varNome.getText().trim();
        String email = varEmail.getText().trim();
        String telefone = varTel.getText();

        if (!nome.isEmpty() && !email.isEmpty() && telefone.length() >= 12) {
            if (controlador.validaCliente(cliente, id, nome, email, telefone)) {
                String logradouro = varLogradouro.getText().trim();
                String numero = varNumero.getText().trim();
                String bairro = varBairro.getText().trim();
                String localidade = varLocalidade.getText().trim();
                String uf = varUf.getText().trim();
                if (controlador.validaEnd(cliente, endereco, logradouro, numero, bairro, localidade, uf, varComplemento.getText().trim(), varCep.getText().trim())) {
                    try {
                        session = HibernateUtil.abrirConexao();
                        clienteDao.saveOrAlter(cliente, session);
                        JOptionPane.showMessageDialog(null, "Alteração salva!");
                        
                    } catch (Exception e) {
                        System.out.println("Erro ao salvar Cliente " + e);
                    } finally {
                        session.close();
                    }
                    
                    tab.setSelectedIndex(0);

                } else {
                    // Mostra Asterisco de campos obrigatórios e retira o que estiver preenchido restante abaixo de CEP
                    if (logradouro.isEmpty()) {
                        lbAstLograd.setVisible(true);
                        if (!numero.isEmpty()) {
                            lbAstNum.setVisible(false);
                        }
                        if (!bairro.isEmpty()) {
                            lbAstBairro.setVisible(false);
                        }
                        if (!localidade.isEmpty()) {
                            lbAstLocal.setVisible(false);
                        }
                        if (!uf.isEmpty()) {
                            lbAstUf.setVisible(false);
                        }
                    }
                    if (numero.isEmpty()) {
                        lbAstNum.setVisible(true);
                        if (!logradouro.isEmpty()) {
                            lbAstLograd.setVisible(false);
                        }
                        if (!bairro.isEmpty()) {
                            lbAstBairro.setVisible(false);
                        }
                        if (!localidade.isEmpty()) {
                            lbAstLocal.setVisible(false);
                        }
                        if (!uf.isEmpty()) {
                            lbAstUf.setVisible(false);
                        }
                    }
                    if (bairro.isEmpty()) {
                        lbAstBairro.setVisible(true);
                        if (!localidade.isEmpty()) {
                            lbAstLocal.setVisible(false);
                        }
                        if (!uf.isEmpty()) {
                            lbAstUf.setVisible(false);
                        }
                        if (!numero.isEmpty()) {
                            lbAstNum.setVisible(false);
                        }
                        if (!logradouro.isEmpty()) {
                            lbAstLograd.setVisible(false);
                        }
                    }
                    if (localidade.isEmpty()) {
                        lbAstLocal.setVisible(true);
                        if (!uf.isEmpty()) {
                            lbAstUf.setVisible(false);
                        }
                        if (!numero.isEmpty()) {
                            lbAstNum.setVisible(false);
                        }
                        if (!logradouro.isEmpty()) {
                            lbAstLograd.setVisible(false);
                        }
                        if (!bairro.isEmpty()) {
                            lbAstBairro.setVisible(false);
                        }

                    }
                    if (uf.isEmpty()) {
                        lbAstUf.setVisible(true);
                        if (!numero.isEmpty()) {
                            lbAstNum.setVisible(false);
                        }
                        if (!logradouro.isEmpty()) {
                            lbAstLograd.setVisible(false);
                        }
                        if (!bairro.isEmpty()) {
                            lbAstBairro.setVisible(false);
                        }
                        if (!localidade.isEmpty()) {
                            lbAstLocal.setVisible(false);
                        }
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, "Informe um nome maior que 3 Caracteres");
            }
        } else {
            if (nome.isEmpty()) {
                lbAstName.setVisible(true);
                if (!email.isEmpty()) {
                    lbAstEmail.setVisible(false);
                }
            }
            if (email.isEmpty()) {
                lbAstEmail.setVisible(true);
                if (!nome.isEmpty()) {
                    lbAstName.setVisible(false);
                }
            }
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void varEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varEmailFocusLost
        String email = varEmail.getText().trim();

        if (email.contains("@") && email.contains(".")) {
            String emailBd = "";
            try {
                session = HibernateUtil.abrirConexao();
                System.out.println(email);
                emailBd = clienteDao.askPerEmail(email, session);

            } catch (Exception e) {
                System.out.println("Erro ao verificar e-mail " + e);

            } finally {
                session.close();
            }
            System.out.println(emailBd);
            if (emailBd == null) {
                cliente.setEmail(email);
            } else {

                JOptionPane.showMessageDialog(null, "Email já cadastrado!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Digite um e-mail!");
        }
    }//GEN-LAST:event_varEmailFocusLost

    public void popularTabela(List<Cliente> cliente){
        // Limpando a tabelaModelo
        tabelaModelo.setNumRows(0);
        for (Cliente  client : clientes) {
            tabelaModelo.addRow(new Object[]{client.getId(), client.getNome(), client.getTelefone(), client.getEmail()});
        }
    }    
    
    private void varCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varCepFocusLost
        CepRest cepRest = new CepRest();
        EnderecoDTO enderecoApi = cepRest.pesquisarCep(varCep.getText());
        if (enderecoApi == null) {
            JOptionPane.showMessageDialog(null, "O Cep informado não existe");
        } else {
            varNumero.setEnabled(true);
            varLogradouro.setEnabled(true);
            varBairro.setEnabled(true);
            varLocalidade.setEnabled(true);
            varUf.setEnabled(true);
            varComplemento.setEnabled(true);

            varLogradouro.setText(enderecoApi.getLogradouro());
            varBairro.setText(enderecoApi.getBairro());
            varLocalidade.setText(enderecoApi.getLocalidade());
            varUf.setText(enderecoApi.getUf());
            varComplemento.setText(enderecoApi.getComplemento());
            btSalvar.setEnabled(true);

        }
    }//GEN-LAST:event_varCepFocusLost

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        if (!varAskNome.getText().trim().isEmpty()) {
            try {
                session = HibernateUtil.abrirConexao();
                clientes = clienteDao.askPerName(varAskNome.getText().trim(), session);
            } catch (Exception e) {
                System.out.println("Erro ao pesquisar Nome " + e.getMessage());
            }finally{
                session.close();
            }
            popularTabela(clientes);
        }
        else if(!varAskEmail.getText().trim().isEmpty()){
            try {
                session = HibernateUtil.abrirConexao();
                clientes = clienteDao.askListEmail(varAskEmail.getText().trim(), session);
            } catch (Exception e) {
                System.out.println("Erro ao pesquisar por Email " + e.getMessage());
            }finally{
                session.close();
            }
            popularTabela(clientes);
        }else if(varAskTelefone.getText().trim().length() > 11){
            try {
                session = HibernateUtil.abrirConexao();
                clientes = clienteDao.askPerTell(varAskTelefone.getText().trim(), session);
            } catch (Exception e) {
                System.out.println("Erro ao pesquisar por Telefone " + e.getMessage());
            }finally{
                session.close();
            }
            popularTabela(clientes);
        }else{
            JOptionPane.showMessageDialog(null, "Informe um Filtro para Prosseguir");
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int selecionado = tabelaCliente.getSelectedRow();
        if (selecionado == -1){
            JOptionPane.showMessageDialog(null, "Selecione um cliente para Excluir");
        }else {
            Cliente clienteSelecionado = clientes.get(selecionado);
            try {
                session = HibernateUtil.abrirConexao();
                clienteDao.excluir(clienteSelecionado, session);
                clientes.remove(selecionado);
                popularTabela(clientes);
                JOptionPane.showMessageDialog(null, clienteSelecionado.getNome() + " excluído com sucesso!");
                tab.setSelectedIndex(0);
            } catch (Exception e) {
                System.out.println("Erro ao excluir usuario " + e.getMessage());
            }finally{
                session.close();
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        int selecionado = tabelaCliente.getSelectedRow();
        if (selecionado == -1){
            JOptionPane.showMessageDialog(null, "Selecione um cliente para Alterar");
        }else{
            tab.setEnabledAt(1, true);
            Cliente clienteSelecionado = clientes.get(selecionado);
            varId.setText(String.valueOf(new Long(clienteSelecionado.getId())));
            varNome.setText(clienteSelecionado.getNome());
            varEmail.setText(clienteSelecionado.getEmail());
            varTel.setText(clienteSelecionado.getTelefone());
            varCep.setText(clienteSelecionado.getEnderecos().get(0).getCep());
            varBairro.setText(clienteSelecionado.getEnderecos().get(0).getBairro());
            varLogradouro.setText(clienteSelecionado.getEnderecos().get(0).getLogradouro());
            varNumero.setText(clienteSelecionado.getEnderecos().get(0).getNumero());
            varLocalidade.setText(clienteSelecionado.getEnderecos().get(0).getCidade());
            varUf.setText(clienteSelecionado.getEnderecos().get(0).getEstado());
            varComplemento.setText(clienteSelecionado.getEnderecos().get(0).getComplemento());
            tab.setSelectedIndex(1);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        tab.setEnabledAt(1, false);
    }//GEN-LAST:event_tabMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbAskNome;
    private javax.swing.JLabel lbAstBairro;
    private javax.swing.JLabel lbAstEmail;
    private javax.swing.JLabel lbAstLocal;
    private javax.swing.JLabel lbAstLograd;
    private javax.swing.JLabel lbAstName;
    private javax.swing.JLabel lbAstNum;
    private javax.swing.JLabel lbAstUf;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmail1;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbLocalidade;
    private javax.swing.JLabel lbLogradouro;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbNúmero;
    private javax.swing.JLabel lbTel;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbUf;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JPanel tabAlt;
    private javax.swing.JScrollPane tabList;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTextField varAskEmail;
    private javax.swing.JTextField varAskNome;
    private javax.swing.JFormattedTextField varAskTelefone;
    private javax.swing.JTextField varBairro;
    private javax.swing.JTextField varCep;
    private javax.swing.JTextField varComplemento;
    private javax.swing.JTextField varEmail;
    private javax.swing.JTextField varId;
    private javax.swing.JTextField varLocalidade;
    private javax.swing.JTextField varLogradouro;
    private javax.swing.JTextField varNome;
    private javax.swing.JFormattedTextField varNumero;
    private javax.swing.JFormattedTextField varTel;
    private javax.swing.JTextField varUf;
    // End of variables declaration//GEN-END:variables
}
