/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.senac.entidade.Usuario;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author Vítor
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form testeTest
     */
    public TelaInicial(Usuario usuario) {
        initComponents();
        lbNameUser.setText(usuario.getUser().toUpperCase());
        setExtendedState(MAXIMIZED_BOTH);
        
    }
    
    public TelaInicial(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDP = new javax.swing.JDesktopPane();
        lbUser = new javax.swing.JLabel();
        btTrocaUser = new javax.swing.JButton();
        lbNameUser = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        clienteCadastro = new javax.swing.JMenuItem();
        clienteConsultar = new javax.swing.JMenuItem();
        menuPedido = new javax.swing.JMenu();
        pedidoCadastrar = new javax.swing.JMenuItem();
        pedidoBuscar = new javax.swing.JMenuItem();
        btSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(147, 37, 39));

        jDP.setDesktopManager(null);

        javax.swing.GroupLayout jDPLayout = new javax.swing.GroupLayout(jDP);
        jDP.setLayout(jDPLayout);
        jDPLayout.setHorizontalGroup(
            jDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDPLayout.setVerticalGroup(
            jDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        lbUser.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbUser.setForeground(new java.awt.Color(0, 0, 0));
        lbUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUser.setText("Usuário:");

        btTrocaUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTrocaUser.setForeground(new java.awt.Color(0, 0, 0));
        btTrocaUser.setText("Trocar Usuario");
        btTrocaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTrocaUserActionPerformed(evt);
            }
        });

        lbNameUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbNameUser.setForeground(new java.awt.Color(0, 0, 0));
        lbNameUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        menuBar.setForeground(new java.awt.Color(0, 0, 0));

        menuCliente.setText("Cliente");

        clienteCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clienteCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senac/imagens/CadastrarUsuario.png"))); // NOI18N
        clienteCadastro.setText("Cadastro");
        clienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCadastroActionPerformed(evt);
            }
        });
        menuCliente.add(clienteCadastro);

        clienteConsultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clienteConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senac/imagens/BuscarUsuario.png"))); // NOI18N
        clienteConsultar.setText("Consultar");
        clienteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteConsultarActionPerformed(evt);
            }
        });
        menuCliente.add(clienteConsultar);

        menuBar.add(menuCliente);

        menuPedido.setText("Pedido");

        pedidoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pedidoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senac/imagens/CadastrarPedido.png"))); // NOI18N
        pedidoCadastrar.setText("Cadastrar");
        pedidoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoCadastrarActionPerformed(evt);
            }
        });
        menuPedido.add(pedidoCadastrar);

        pedidoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pedidoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senac/imagens/BuscarPedido.png"))); // NOI18N
        pedidoBuscar.setText("Buscar");
        pedidoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoBuscarActionPerformed(evt);
            }
        });
        menuPedido.add(pedidoBuscar);

        menuBar.add(menuPedido);

        btSair.setText("Sair");
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        menuBar.add(btSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                        .addComponent(btTrocaUser)
                        .addContainerGap())
                    .addComponent(jDP)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btTrocaUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbNameUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDP))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCadastroActionPerformed
        CadastroCliente cadCliente = new CadastroCliente();
        
        jDP.add(cadCliente);
        cadCliente.setVisible(true);
        centralizaForm(cadCliente);
    }//GEN-LAST:event_clienteCadastroActionPerformed

    private void btTrocaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTrocaUserActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btTrocaUserActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        dispose();
    }//GEN-LAST:event_btSairMouseClicked

    private void clienteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteConsultarActionPerformed
        ConsultaCliente consultaCliente = new ConsultaCliente();
        jDP.add(consultaCliente);
        consultaCliente.setVisible(true);
        centralizaForm(consultaCliente);
        
    }//GEN-LAST:event_clienteConsultarActionPerformed

    private void pedidoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoCadastrarActionPerformed
        CadastroPedido cadastroPedido =  new CadastroPedido();
        jDP.add(cadastroPedido);
        cadastroPedido.setVisible(true);
        centralizaForm(cadastroPedido);
    }//GEN-LAST:event_pedidoCadastrarActionPerformed

    private void pedidoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoBuscarActionPerformed
        ConsultaPedido consultaPedido = new ConsultaPedido();
        jDP.add(consultaPedido);
        consultaPedido.setVisible(true);
        centralizaForm(consultaPedido);
    }//GEN-LAST:event_pedidoBuscarActionPerformed

    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = jDP.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btSair;
    private javax.swing.JButton btTrocaUser;
    private javax.swing.JMenuItem clienteCadastro;
    private javax.swing.JMenuItem clienteConsultar;
    private javax.swing.JDesktopPane jDP;
    private javax.swing.JLabel lbNameUser;
    private javax.swing.JLabel lbUser;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuPedido;
    private javax.swing.JMenuItem pedidoBuscar;
    private javax.swing.JMenuItem pedidoCadastrar;
    // End of variables declaration//GEN-END:variables
}
